<img src=./../figuras/python3.jpg align=left><BR><BR><BR><BR><BR><BR>
<h1>Numpy</h1>
<img src=./../figuras/python-logo.png align=left>

<h1>Tabla de Contenido<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Conceptos-básicos" data-toc-modified-id="Conceptos-básicos-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Conceptos básicos</a></span></li><li><span><a href="#Creación-de-algunos-arreglos-clásicos" data-toc-modified-id="Creación-de-algunos-arreglos-clásicos-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creación de algunos arreglos clásicos</a></span></li><li><span><a href="#Operaciones-elementales" data-toc-modified-id="Operaciones-elementales-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Operaciones elementales</a></span></li><li><span><a href="#Operaciones-especiales" data-toc-modified-id="Operaciones-especiales-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Operaciones especiales</a></span><ul class="toc-item"><li><span><a href="#Operaciones-entre-matrices-de-diferente-tamaño-(Broadcasting)" data-toc-modified-id="Operaciones-entre-matrices-de-diferente-tamaño-(Broadcasting)-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Operaciones entre matrices de diferente tamaño (Broadcasting)</a></span></li></ul></li><li><span><a href="#Módulo-de-álgebra-lineal" data-toc-modified-id="Módulo-de-álgebra-lineal-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Módulo de álgebra lineal</a></span><ul class="toc-item"><li><span><a href="#Más-matrices-especiales" data-toc-modified-id="Más-matrices-especiales-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Más matrices especiales</a></span></li></ul></li><li><span><a href="#Módulo-linalg" data-toc-modified-id="Módulo-linalg-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Módulo <code>linalg</code></a></span></li><li><span><a href="#Una-primera-aplicación" data-toc-modified-id="Una-primera-aplicación-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Una primera aplicación</a></span></li></ul></div>

Para instalar NumPy en Windows y Ubuntu, puedes seguir estos pasos:

**Windows:**

1. Abre una ventana de línea de comandos (Command Prompt) con privilegios de administrador. Puedes hacerlo buscando "Command Prompt" en el menú de inicio, haciendo clic derecho en él y seleccionando "Ejecutar como administrador".

2. En la ventana de línea de comandos, ingresa el siguiente comando para instalar NumPy utilizando pip, que es el sistema de gestión de paquetes de Python:

   ```bash
   pip install numpy
   ```

3. Espera a que la instalación se complete. Una vez finalizada, NumPy estará instalado en tu sistema.

**Ubuntu:**

1. Abre una terminal. Puedes hacerlo presionando `Ctrl + Alt + T` o buscando "Terminal" en el menú de aplicaciones.

2. Actualiza la lista de paquetes utilizando el siguiente comando:

   ```bash
   sudo apt update
   ```

3. Instala el paquete `python3-numpy` utilizando el siguiente comando:

   ```bash
   sudo apt install python3-numpy
   ```

   Si estás usando Python 2 (lo cual no se recomienda, ya que ha llegado a su fin de vida), el nombre del paquete sería `python-numpy`.

4. Confirma la instalación ingresando `Y` si se te solicita y espera a que se complete.

Una vez que hayas seguido estos pasos, NumPy estará instalado en tu sistema y podrás importarlo en tus scripts de Python para realizar cálculos numéricos y manipulación de arreglos multidimensionales.

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Paquete Numpy

[Numpy](https://numpy.org/) es la librería central para la computación científica en Python, nos permite acceder a una gran cantidad de funciones matemáticas y crear arreglos multidimensionales de alta eficiencia. Es un paquete facil de utilizar y posee una de las [documentaciones](https://numpy.org/doc/) más robustas de Python, quizás es uno de los paquetes más usados.  Su ancestro es un paquete llamado Numeric, creado por [Jim Hugunin](https://en.wikipedia.org/wiki/Jim_Hugunin) y en 2005, con la incorporación de Numarray y varias modificaciones, [Travis Oliphant](https://en.wikipedia.org/wiki/Travis_Oliphant) lo transforma en Numpy.

In [3]:
import numpy as np

## Conceptos básicos

El objeto más importante de numpy es el arreglo multidimensional homogéneo, es decir, una tabla de elementos del mismo tipo, indexados por una tupla de enteros no negativos. En numpy las dimensiones del arreglo las llamaremos ejes (axes).

**Ejemplo**

Un elemento en $\mathbb{R}^n$ es un arreglo $n$-dimensional con un solo eje:



In [4]:
V=np.array([2,1,4])
print(V)

[2 1 4]


In [5]:
BV=np.array([True,False,True])
print(BV)

[ True False  True]


Una matriz de tamaño $n\times m$ es un arreglo de dos ejes:

In [6]:
M=np.array([[1,0,1],[0,1,0],[2,1,3]])
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


In [7]:
M.dtype

dtype('int64')

In [8]:
M.shape

(3, 3)

En casos más generales podriamos definir un tensor:

In [9]:
T=np.array([[[1,0,1],[0,1,0]],[[1,2,3],[2,1,4]]])
print(T)

[[[1 0 1]
  [0 1 0]]

 [[1 2 3]
  [2 1 4]]]


La exploración de elementos que conforman al arreglo es similar a la de las listas de Python, con la salvedad de que en la matriz, o el tensor no tengo una lista de listas:

In [10]:
V[0]

np.int64(2)

In [11]:
print(M)

[[1 0 1]
 [0 1 0]
 [2 1 3]]


In [12]:
M[1,1]

np.int64(1)

In [13]:
M[1][1]

np.int64(1)

In [14]:
print(T)

[[[1 0 1]
  [0 1 0]]

 [[1 2 3]
  [2 1 4]]]


In [15]:
T[1,1,2]

np.int64(4)

In [16]:
T[1][1][2]

np.int64(4)

In [17]:
TT=[[[1,0,1],[0,1,0]],[[1,2,3],[2,1]]]

Forma incorrecta de buscar un elemento anidado

In [ ]:
TT[1,1,1]
# TypeError: list indices must be integers or slices, not tuple

TypeError: list indices must be integers or slices, not tuple

In [19]:
TT[1][1][1]

1

Podemos usar también índices de sublistas

In [20]:
M2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
M2[:2,1:3]

array([[2, 3],
       [6, 7]])

In [22]:
T=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32],[33,34,35,36]]])
print(T)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [23]:
T[:2,1:,1:3]

array([[[ 6,  7],
        [10, 11]],

       [[18, 19],
        [22, 23]]])

También podemos extraer elementos utilizando listas

In [24]:
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
M2[[0,2],[1,3]]

array([ 2, 12])

Extraer filas

In [26]:
M2[np.array([0,2])]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

Extraer columnas

In [27]:
M2[:,np.array([2,0])]

array([[ 3,  1],
       [ 7,  5],
       [11,  9]])

Algunos comandos elementales son:

* `.ndim` (número de ejes del arreglo)

In [28]:
V.ndim

1

In [29]:
M.ndim

2

In [30]:
T.ndim

3

* `.shape` (La dimensión del arreglo. Obtenemos una tupla de enteros)

In [31]:
V.shape

(3,)

In [32]:
M.shape

(3, 3)

In [33]:
T.shape

(3, 3, 4)

* `.size` (El número total de elementos que conforman al arreglo)

In [34]:
V.size

3

In [38]:
T.size

36

* `.dtype` (el tipo de lementos en el arreglo)

In [35]:
M.dtype

dtype('int64')

In [36]:
A=np.array([3<2,2<3,4<5])
print(A)

[False  True  True]


In [37]:
A.dtype

dtype('bool')

In [38]:
TT2=np.array([A,V])
print(TT2)

[[0 1 1]
 [2 1 4]]


In [43]:
TT2.dtype

dtype('int64')

## Creación de algunos arreglos clásicos

Tenemos la oportunidad de utilizar algunas funciones de Numpy para generar arreglos y matrices conocidas:


In [39]:
ceros=np.zeros((2,3))
print(ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
unos=np.ones((2,2,3))
print(unos)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [41]:
constante=np.full((4,3),5)
print(constante)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [42]:
constante2=np.full((4,3),5<2)
print(constante2)

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [43]:
constante3=np.full((4,3),"Hola")
print(constante3)

[['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']
 ['Hola' 'Hola' 'Hola']]


In [44]:
identidad=np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
aleatoria = np.random.random((2,2))  
print(aleatoria) 

[[0.88773616 0.73722632]
 [0.02548787 0.7261323 ]]


In [46]:
?np.random.randn

Signature: np.random.randn(*args)
Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned 

## Operaciones elementales

Podemos hacer operaciones matriciales elementales:

In [47]:
x = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
y = np.array([[7,8,9],[9,8,7]], dtype=np.float64)

In [48]:
print(x)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[7. 8. 9.]
 [9. 8. 7.]]


In [49]:
print(x + y)

[[ 8. 10. 12.]
 [13. 13. 13.]]


In [50]:
print(x - y)

[[-6. -6. -6.]
 [-5. -3. -1.]]


In [51]:
print(x*y) #multiplicación elemento a elemento

[[ 7. 16. 27.]
 [36. 40. 42.]]


In [52]:
print(x / y) #división elemento a elemento

[[0.14285714 0.25       0.33333333]
 [0.44444444 0.625      0.85714286]]


In [53]:
print(np.sqrt(y))  #raíz cuadrada elemento a elemento

[[2.64575131 2.82842712 3.        ]
 [3.         2.82842712 2.64575131]]


In [54]:
print(np.transpose(y)) #transpuesta

[[7. 9.]
 [8. 8.]
 [9. 7.]]


In [55]:
print(y.T) #transpuesta

[[7. 9.]
 [8. 8.]
 [9. 7.]]


In [56]:
print(x@np.transpose(y)) #multiplicación de matrices

[[ 50.  46.]
 [122. 118.]]


In [57]:
print(x.dot(y.T)) #multiplicación de matrices

[[ 50.  46.]
 [122. 118.]]


In [58]:
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [59]:
print(np.sum(x))   #suma de todos los elementos
print(np.sum(x, axis=0))  #suma de elementos por columnas
print(np.sum(x, axis=1))   #suma de elementos por filas

21.0
[5. 7. 9.]
[ 6. 15.]


Mas funciones [aquí](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

## Operaciones especiales

En ocasiones tenemos que hacer algunas operaciones que no tienen en cuenta la forma de las matrices o que involucran matrices de diferentes tamaños. Aquí algunos ejemplos:

In [60]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
v = np.array([1, 0, 1])
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [61]:
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [62]:
x+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

* Suma de un vector a una fila

In [63]:
x[0]=x[0]+v
print(x)

[[ 2  2  4]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Multiplicar una fila por escalar

In [64]:
x[0]=x[0]*2
print(x)

[[ 4  4  8]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Intercambiar filas

In [65]:
fc=x.copy()
x[1]=x[0]
x[0]=fc[1]
print(x)


[[ 4  5  6]
 [ 4  4  8]
 [ 7  8  9]
 [10 11 12]]


### Operaciones entre matrices de diferente tamaño (Broadcasting)

NumPy transforma los arreglos involucrados para que tengan el mismo tamaño y, por tanto, puedan someterse a las operaciones por elementos sin generar excepciones.

In [66]:
a = np.arange(0.2, 40.2, 10.5)
a.shape

(4,)

In [67]:
print(a)

[ 0.2 10.7 21.2 31.7]


In [68]:
a = a[:, np.newaxis]  #Adicionamos un eje
print(a.shape)
a

(4, 1)


array([[ 0.2],
       [10.7],
       [21.2],
       [31.7]])

In [69]:
b = np.array([0, 1, 2])
print(b)

[0 1 2]


In [70]:
a+b

array([[ 0.2,  1.2,  2.2],
       [10.7, 11.7, 12.7],
       [21.2, 22.2, 23.2],
       [31.7, 32.7, 33.7]])

In [71]:
A=np.array([[0,1],[1,2]])
B=np.array([[2,1],[1,2]])

In [72]:
A= A[:,:, np.newaxis] 

In [73]:
A

array([[[0],
        [1]],

       [[1],
        [2]]])

In [74]:
A+B

array([[[2, 1],
        [2, 3]],

       [[3, 2],
        [3, 4]]])

## Módulo de álgebra lineal



### Más matrices especiales

Tenemos la posibilidad de buscar más matrices interesantes en Numpy.

* Matriz triangular

In [75]:
np.triu(np.ones((3,3)))

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [76]:
np.triu(np.ones((3,3)),1)

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [77]:
np.triu(np.ones((3,3)),2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
M3=(a+b).T
print(M3)

[[ 0.2 10.7 21.2 31.7]
 [ 1.2 11.7 22.2 32.7]
 [ 2.2 12.7 23.2 33.7]]


In [79]:
np.triu(M3)

array([[ 0.2, 10.7, 21.2, 31.7],
       [ 0. , 11.7, 22.2, 32.7],
       [ 0. ,  0. , 23.2, 33.7]])

In [80]:
np.tril(M3)

array([[ 0.2,  0. ,  0. ,  0. ],
       [ 1.2, 11.7,  0. ,  0. ],
       [ 2.2, 12.7, 23.2,  0. ]])

In [81]:
np.tril(M3,-1)

array([[ 0. ,  0. ,  0. ,  0. ],
       [ 1.2,  0. ,  0. ,  0. ],
       [ 2.2, 12.7,  0. ,  0. ]])

* Matriz diagonal

In [82]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Módulo `linalg` 

Numpy tiene un módulo especializado en funciones de [álgebra lineal](https://numpy.org/doc/stable/reference/routines.linalg.html)

* Potencias de matrices

In [83]:
N = np.array([[1, 0, 1], [2, -1, 3], [4, 3, 2]])
print(N)
np.linalg.matrix_power(N,2)

[[ 1  0  1]
 [ 2 -1  3]
 [ 4  3  2]]


array([[ 5,  3,  3],
       [12, 10,  5],
       [18,  3, 17]])

* Determinantes



In [84]:
np.linalg.det(N)

np.float64(-1.0000000000000009)

* Valores y vectores propios

In [85]:
np.linalg.eig(N)

EigResult(eigenvalues=array([ 4.84625207,  0.070739  , -2.91699107]), eigenvectors=array([[ 0.21740883,  0.64484788, -0.15390745],
       [ 0.50347557, -0.47443887, -0.78286616],
       [ 0.83620915, -0.59923199,  0.60285411]]))

* Rango

In [86]:
np.linalg.matrix_rank(N)


np.int64(3)

* Solución de sistemas de ecuaciones lineales

In [87]:
np.linalg.solve(N, [1,2,3])

array([ 2., -1., -1.])

In [88]:
print(N)

[[ 1  0  1]
 [ 2 -1  3]
 [ 4  3  2]]


* Matrices Inversas



In [89]:
Ninv=np.linalg.inv(N)
Ninv

array([[ 11.,  -3.,  -1.],
       [ -8.,   2.,   1.],
       [-10.,   3.,   1.]])

Comprobamos este resultado:

In [90]:
Ninv @ N

array([[ 1.00000000e+00,  9.99200722e-16, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11022302e-15,  1.00000000e+00]])

Observe que la anterior es la matriz idéntica.

In [91]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [92]:
?np.trace

Signature:       np.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
Call signature:  np.trace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function trace at 0x00000297FEF0D440>
File:            c:\dev\edu\diplomado\diplomado en big data, analytics y business intelligence v1\mod 2\04-tareas\python avanzado\.venv\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return the sum along diagonals of the array.

If `a` is 2-D, the sum along its diagonal with the given offset
is returned, i.e., the sum of elements ``a[i,i+offset]`` for all i.

If `a` has more than two dimensions, then the axes specified by axis1 and
axis2 are used to determine the 2-D sub-arrays whose traces are returned.
The shape of the resulting array is the same as that of `a` with `axis1`
and `axis2` removed.

Parameters
----------
a : array_like
    Input array, from which the diagonals are taken.
offset : int, optional
    Offset of the diagonal from the main diagon

# Herramientas interactivas `ipywidgets`

Otro paquete que será transversal en este curso y nos permitira crear interfaces interesantes para nuestros estudiantes es [ipywidgets`](https://ipywidgets.readthedocs.io/en/stable/). Para instalar desde el cuaderno escriba:

In [93]:
%pip install ipywidgets
# %jupyter nbextension enable --py widgetsnbextension
# Segunda linea comentada por que se ejecuto el notebook en vscode

Note: you may need to restart the kernel to use updated packages.


Importemos el paquete

In [94]:
from ipywidgets import interact
import ipywidgets as widgets

La herramienta más básica de este paquete es la función `interact`. En el siguiente ejemplo veamos su utilidad:

In [95]:
def f(x):
    print("El valor que escogió es", x)
    return x

In [96]:
interact(f, x=1.2)

interactive(children=(FloatSlider(value=1.2, description='x', max=3.5999999999999996, min=-1.2), Output()), _d…

<function __main__.f(x)>

In [97]:
interact(f, x=True)

interactive(children=(Checkbox(value=True, description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.f(x)>

In [98]:
interact(f, x=['Elemento 1','Elemento 2'])

interactive(children=(Dropdown(description='x', options=('Elemento 1', 'Elemento 2'), value='Elemento 1'), Out…

<function __main__.f(x)>

In [99]:
interact(f, x='Soy interactivo')

interactive(children=(Text(value='Soy interactivo', description='x'), Output()), _dom_classes=('widget-interac…

<function __main__.f(x)>

Los elementos que permiten la interacción con el usuario son los widgets, una lista completa de ellos se encuentra [aquí.](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html)

A continuación hacemos un cambio sobre el widget:

In [100]:
interact(f, x=widgets.IntText(
    value=7,
    description='El valor que quiera:',
    disabled=False
));

interactive(children=(IntText(value=7, description='El valor que quiera:'), Output()), _dom_classes=('widget-i…

## Una primera aplicación

Ya que conocemos algo de Numpy y ipywidgets vamos a crear un ejemplo muy sencillo para calcular algunos estadísticos elementales de una lista de valores:

In [101]:
def estadisticos(x):
    L=x.split()
    L=[float(i) for i in L]        
    x=np.array(list(L))
    print("La media es", np.mean(x))
    print("La mediana es", np.median(x))
    print("La varianza poblacional es", np.var(x))
    print("La varianza muestral es", np.var(x,ddof=1))
    print("La desviación estándar poblacional es", np.std(x))
    print("La desviación estándar muestral es", np.std(x,ddof=1))
    return

In [102]:
"Hola   ¿cómo están?".split()

['Hola', '¿cómo', 'están?']

In [103]:
estadisticos("1 2 3")

La media es 2.0
La mediana es 2.0
La varianza poblacional es 0.6666666666666666
La varianza muestral es 1.0
La desviación estándar poblacional es 0.816496580927726
La desviación estándar muestral es 1.0


Evalue los estadísticos del conjunto de datos [1,1,2,3] y compruebelo con la herramienta:

In [104]:
interact(estadisticos,x="1 2 3")

interactive(children=(Text(value='1 2 3', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.estadisticos(x)>

In [105]:
def estadisticos(x):
    try:
        L=x.split()
        L=[float(i) for i in L]        
        x=np.array(list(L))
        print("La media es", np.mean(x))
        print("La mediana es", np.median(x))
        print("La varianza poblacional es", np.var(x))
        print("La varianza muestral es", np.var(x,ddof=1))
        print("La desviación estándar poblacional es", np.std(x))
        print("La desviación estándar muestral es", np.std(x,ddof=1))
    except:
        print("Cuidado con lo que escribe, solo se admiten valores numéricos")
    return

In [106]:
interact(estadisticos,x="1 2 3")

interactive(children=(Text(value='1 2 3', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.estadisticos(x)>

In [107]:
def txttomtx(x):
    L=x.split()
    L=[float(i) for i in L]
    e=np.sqrt(len(L))
    d=int(e)
    k=0
    M=np.zeros((d,d))
    for i in range(d):
        for j in range(d):
            M[i,j]=L[k]
            k=k+1
    return M

In [108]:
txttomtx("1 2 3 4")

array([[1., 2.],
       [3., 4.]])

In [109]:
M=txttomtx("1 2 3 4")

In [116]:
M

array([[1., 2.],
       [3., 4.]])

In [110]:
np.linalg.det(M)

np.float64(-2.0000000000000004)

In [111]:
def matrizopun(x,y):
    try:
        M=txttomtx(x)
        M2=txttomtx(y)
        SM=M+M2
        print("La suma es:",SM)
    except:
        print("Cuidado con lo que escribe, solo se admiten valores numéricos")
    return

In [112]:
interact(matrizopun,x="1 2 3 4",y="1 2 3 4")

interactive(children=(Text(value='1 2 3 4', description='x'), Text(value='1 2 3 4', description='y'), Output()…

<function __main__.matrizopun(x, y)>

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Python 3 para Desarrolladores</span> por <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Marcelo Invert Palma Salas</span> se distribuye bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional</a>.

### Que significa la licencia arriba:

Compartir: copia y redistribuye el material en cualquier medio o formato <b>haciendo referencia al autor</b>.
Adaptarse: remezclar, transformar y construir sobre el material para usos <b>no comerciales</b> que aporten al OpenSource.
El licenciante no puede revocar estas libertades siempre que siga los términos de la licencia.